config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :professionals 

end

app/models/professional.rb
class Professional < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  respond_to :json,:html

  def index
    @professionals = Professional.paginate(page: params[:page], per_page: 20)
    respond_with @professionals
  end

  def show
    @professional = Professional.find(params[:id])
    respond_with @professional
  end

  def search

  end

  def create
    params["professional"]["skills"]  = params["professional"]["skills"].split(",")
    params["professional"]["hobbies"] = params["professional"]["hobbies"].split(",")
    @result = Profesional.create(params)
    redirect_to :professional
  end

  def new
    @professional = Professional.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper

  def gender_list
    [
    "Male",
    "Female",
    "Agender/Neutrois",
    "Androgyne/Androgynous",
    "Bigender",
    "Cis/Cisgender",
    "Female to Male/FTM",
    "Gender Fluid",
    "Gender Nonconforming/Variant",
    "Gender Questioning",
    "Genderqueer",
    "Intersex",
    "Male to Female/MTF",
    "Neither",
    "Non-binary",
    "Other",
    "Pangender",
    "Trans/Transgender",
    "Transsexual",
    "Two-spirit"
  ]


  end

  def subject_areas
    ["Physics", "Math", "Chemistry", "Biology"]
  end
end

app/views/home/index.html.erb
<!DOCTYPE HTML>
<html>

<head>
	<link rel="stylesheet" type="text/css" href="app/assests/stylesheets/style.css">
</head>


<body><h1>eGuidance</h1>
<a href='/professionals'>People</a>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EGuidance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/professionals/index.html.erb
<ul class='list-group'>

  <% @professionals.each do |prof| %>

    <li class='list-group-item'><%=link_to("#{prof.first_name} #{prof.last_name}", prof) %> <span class='badge push-right'><%=prof.subject_area %></span> </li>

  <%end%>

  <li class='list-group-item'><%=link_to("new", new_professional_path)%></li>
</ul>
<%= will_paginate @professionals %>

app/views/professionals/new.html.erb
<%= form_for @professional do |p| %>
  <%= p.label :first_name %>:
  <%= p.text_field :first_name %><br />

  <%= p.label :last_name %>:
  <%= p.text_field :last_name %><br />

  <%= p.label :degree_subject %>:
  <%= p.text_field :degree_subject %><br />

  <%= p.label  :degree_level %>:
  <%= p.select :degree_level, options_for_select([["bacholers","bacholers"], ["masters","masters"] , ["phd","phd"]])%> <br />

  <%= p.label :age %>:
  <%= p.number_field :age%><br />

  <%= p.label :first_language %>:
  <%= p.select "first_language", options_from_collection_for_select(LanguageList::COMMON_LANGUAGES, "iso_639_1", "name") %><br />

  <%= p.label :skills %> (comma seperated):
  <%= p.text_field :skills %><br />


  <%= p.label :gender %>:
  <%= p.select :gender, options_for_select(gender_list)%><br />

  <%= p.label :place_of_origin %>:
  <%= country_select(:professional, :place_of_origin)%><br />

  <%= p.label :hobbies%>(comma seperated):
  <%= p.text_field :hobbies %><br />

  <%= p.label :university%>:
  <%= p.text_field :university %><br />

  <%= p.label :ethnicity%>:
  <%= p.text_field :ethnicity %><br />

  <%= p.label :subject_area%>:
  <%= p.select  :subject_area, options_for_select(subject_areas)%><br />

  <%= p.label :profile_pic_url%>:
  <%= p.url_field :profile_pic_url%><br />

  <%= p.label :employer%>:
  <%= p.text_field :employer%>


<%= p.submit %>
<% end %>

app/views/professionals/show.html.erb
<div class='panel'>
  <div class='panel-heading'>
    <%=image_tag(@professional.profile_pic_url, width: 150)%>
    <%= @professional.first_name%>, <%= @professional.last_name %>
  </div>
  <div class='panel-body'>
    <ul class='list-group'>

      <li class='list-group-item'><span class='key'>Degree Subject </span><span class='badge push-right'><%= @professional.degree_subject%></span></li>
      <li class='list-group-item'><span class='key'>Degree Level </span>  <span class='badge push-right'><%= @professional.degree_level%></span></li>
      <li class='list-group-item'><span class='key'>Age </span>           <span class='badge push-right'><%= @professional.age %></span></li>
      <li class='list-group-item'><span class='key'>First Language </span>  <span class='badge push-right'><%= @professional.first_language%></span></li>
      <li class='list-group-item'><span class='key'>Skills" </span>  <span class='badge push-right'><%= @professional.skills.join(", ")%></span></li>
      <li class='list-group-item'><span class='key'>Place Of Origin </span>  <span class='badge push-right'><%= @professional.place_of_origin%></span></li>
      <li class='list-group-item'><span class='key'>Gender </span>  <span class='badge push-right'><%= @professional.gender%></span></li>
      <li class='list-group-item'><span class='key'>Hobbies </span>  <span class='badge push-right'><%= @professional.hobbies.join(", ")%></span></li>
      <li class='list-group-item'><span class='key'>University </span> <span class='badge push-right'> <%= @professional.university%></span></li>
      <li class='list-group-item'><span class='key'>Ethnicity </span>  <span class='badge push-right'><%= @professional.ethnicity%></span></li>
      <li class='list-group-item'><span class='key'>Subject Area </span> <span class='badge push-right'> <%= @professional.subject_area%></span></li>
      <li class='list-group-item'><span class='key'>Employer </span>  <span class='badge push-right'><%= @professional.employer%></span></li>

    </ul>
  </div>
</div>